---
title: "AirBnB_datasets"
author: "Ellie Schmucker, with edits by Kayla Freeman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
library(tidyverse)
library(skimr)

nyc_2024 <- read.csv("nyc_mar2024.csv")

nyc_2024 <- nyc_2024 %>%
  select(id, name, host_id, host_name, neighborhood_overview, neighbourhood_cleansed, neighbourhood_group_cleansed,latitude, longitude, room_type, price, last_scraped, last_review, minimum_nights, number_of_reviews, last_review, reviews_per_month, reviews_per_month, calculated_host_listings_count, availability_365, number_of_reviews_ltm, license, host_location, host_since, host_neighbourhood, host_listings_count, host_total_listings_count,  number_of_reviews_l30d )
head(nyc_2024)

filtered_nyc_2024 <- nyc_2024 %>%
  mutate(last_review_date = as.Date(last_review)) %>%
  filter(last_review_date >= max(last_review_date, na.rm = T) %m-% months(6) )
filtered_nyc_2024$price = as.numeric(filtered_nyc_2024$price)
#
filtered_nyc_2024 %>% select(last_review_date) %>% summary()



dim(nyc_2023)
filtered_nyc_2024$price
```


